# Generated by Django 5.1.1 on 2025-01-13 18:12

import habits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habits_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="is_daily",
        ),
        migrations.AddField(
            model_name="habits",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневная"),
                    ("weekly", "Еженедельная"),
                    ("monthly", "Ежемесячная"),
                ],
                default="daily",
                max_length=10,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="duration",
            field=models.IntegerField(
                validators=[habits.models.validate_duration],
                verbose_name="Продолжительность в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(verbose_name="Время, когда надо выполнить привычку"),
        ),
    ]
